apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: service-example
  namespace: service-example
spec:
  releaseName: service-example
  chart:
    spec:
      chart: service-example
      version: ">=0.1.0"
      sourceRef:
        kind: HelmRepository
        name: service-example-chart
        namespace: service-example
  interval: 5m
  install:
    createNamespace: true
  values:
    # Add custom values here if needed
