---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: v1.10.1
  values:
    persistence:
      defaultDataLocality: best-effort
    csi:
      kubeletRootDir: /var/snap/microk8s/common/var/lib/kubelet
  interval: 1m0s
  
